from enum import StrEnum


class DomainDecisionType(StrEnum):
    APPROVE = "APPROVE"
    CONDITIONAL_APPROVAL = "CONDITIONAL_APPROVAL"
    REWORK_REQUIRED = "REWORK_REQUIRED"
    HOLD = "HOLD"
    NOT_EVALUATED = "NOT_EVALUATED"


class LifecycleStatus(StrEnum):
    RECEIVED = "RECEIVED"
    VALIDATING = "VALIDATING"
    VALIDATION_FAILED = "VALIDATION_FAILED"
    REWORK_REQUIRED = "REWORK_REQUIRED"
    READY_FOR_APPROVAL = "READY_FOR_APPROVAL"
    PENDING_HUMAN_APPROVAL = "PENDING_HUMAN_APPROVAL"
    APPROVED = "APPROVED"
    ERP_HANDOFF_READY = "ERP_HANDOFF_READY"
    CREATED_IN_ERP_SIMULATED = "CREATED_IN_ERP_SIMULATED"
    ON_HOLD = "ON_HOLD"
    CANCELLED = "CANCELLED"


class Severity(StrEnum):
    NONE = "NONE"
    INFO = "INFO"
    WARNING = "WARNING"
    CRITICAL = "CRITICAL"


class AssessmentStatus(StrEnum):
    PASS = "PASS"
    PASS_WITH_WARNINGS = "PASS_WITH_WARNINGS"
    FAIL = "FAIL"
    NOT_EVALUATED = "NOT_EVALUATED"


class ReworkSource(StrEnum):
    VENDOR = "VENDOR"
    INTERNAL = "INTERNAL"
    SYSTEM = "SYSTEM"


class ReworkReason(StrEnum):
    SUBMISSION_DEFECT = "SUBMISSION_DEFECT"
    CATALOG_QUALITY_DEFECT = "CATALOG_QUALITY_DEFECT"
    POLICY_FAILURE = "POLICY_FAILURE"
    HUMAN_REJECTION = "HUMAN_REJECTION"
    ERP_RETURN_SIMULATION = "ERP_RETURN_SIMULATION"
    VENDOR_REQUESTED_AMENDMENT = "VENDOR_REQUESTED_AMENDMENT"
    INTERNAL_CORRECTION = "INTERNAL_CORRECTION"
